window.PUFFS_PRODUCTION = {
  characters: [
    {name:'Wayne Hopkins',track:'Wayne only',description:'An earnest underdog who arrives convinced he may be the hero. He is open, awkward, loyal, deeply affected by failure, and eventually brave enough to choose his friends over recognition.'},
    {name:'Oliver Rivers',track:'Oliver only',description:'A math savant who is suddenly bad at school for the first time. Dry, anxious, precise, and sincere; Wayne’s best friend and Megan’s eventual partner.'},
    {name:'Megan Jones',track:'Megan only',description:'Defensive, sarcastic, and determined not to be a Puff. Her toughness protects real loneliness and a longing for her mother; over seven years she becomes fiercely loyal to the people she tried to reject.'},
    {name:'Narrator',track:'Narrator only',description:'Directly guides the audience through all seven years. Needs command, pace, clear storytelling, and the flexibility to move from jokes and interruptions into the final emotional turn.'},
    {name:'Ernie Mac',track:'A Very Tall Man · Seamus · A Certain Potions Teacher · Professor Turban · Ghost History Teach · Professor Locky · Mr. Nick · Sal · Second Headmaster · Real Mr. Moody',description:'Ernie is loud, proud, and convinced he is basically the best. This track carries many authority figures and needs immediate, fearless vocal and physical transformation.'},
    {name:'Hannah',track:'First Headmaster · Professor McG · Professor Sproutty · Xavia Jones · Professor Lanny · Runes Teach · Ms. Babble',description:'Hannah is quiet, awkward, and accustomed to being bullied. Her doubles span eccentric teachers, powerful adults, and the genuinely dangerous—but deeply Puff-like—Xavia Jones.'},
    {name:'J. Finch Fletchley',track:'Uncle Dave · Goyle · A Fat Friar · Clumsy Longbottom · Hermeoone #3 · Viktor · Mr. Bagman · Zach Smith',description:'Boyish, exuberant, idiosyncratic, and completely sincere. The doubled roles demand bold physical choices, clean contrasts, and strong comic instincts.'},
    {name:'Sally Perks',track:'Hermeoone · Blondo Malfoy · Rowena · Rita Scooter · Bippy',description:'Sally is pleasant and comparatively ordinary, with terrible eyesight once she abandons her glasses. Her doubles are sharper caricatures that must read instantly.'},
    {name:'Susie Bones',track:'Harry · Colin · Hermeoone #2 · Ric Gryff · Myrtle',description:'Susie expects death at every turn. Her gloomy stillness must contrast completely with Harry’s swagger, physical confidence, and constant intrusion into the Puffs’ story.'},
    {name:'Leanne',track:'Ginny · Helga · Frenchy',description:'At first she seems gloriously random and disconnected. Her sincerity, enthusiasm, and unexpected clarity grow into the courage that rallies the Puffs when everyone else is ready to leave.'},
    {name:'Cedric / Mr. Voldy',track:'Cedric · Mr. Voldy',description:'Cedric is sunny, athletic, kind, slightly dim, and the ideal Puff. Mr. Voldy is a deliberately theatrical opposite: dangerous, ridiculous, physical, and still a real threat.'},
    {name:'Death Buddies',track:'Played by the company',description:'The full company becomes the masked army during the final battle. The work depends on ensemble precision, fast entrances, physical storytelling, and clean switches between named roles and attackers.'}
  ],
  scenes: [
    {act:'Act I',year:'',name:'Prologue',pages:'1–5'},
    {act:'Act I',year:'Year One',name:'Welcome to the Puffs',pages:'5–10'},
    {act:'Act I',year:'Year One',name:'Studies',pages:'10–12'},
    {act:'Act I',year:'Year One',name:'The Feast!',pages:'13–15'},
    {act:'Act I',year:'Year One',name:'Back in the Common Room',pages:'15'},
    {act:'Act I',year:'Year One',name:'A Trio Is Born',pages:'15–22'},
    {act:'Act I',year:'Year One',name:'Wayne & Cedric',pages:'22–23'},
    {act:'Act I',year:'Year One',name:'Sports!',pages:'22'},
    {act:'Act I',year:'Year One',name:'The End of the Year',pages:'22–23'},
    {act:'Act I',year:'Year Two',name:'Year Two',pages:'23–25'},
    {act:'Act I',year:'Year Two',name:'Dueling Club & Harry Wants to Kill Everyone',pages:'25–26'},
    {act:'Act I',year:'Year Two',name:'More Terror in the Common Room',pages:'26–27'},
    {act:'Act I',year:'Year Two',name:'The Heir of Snakes',pages:'27–29'},
    {act:'Act I',year:'Year Two',name:'A Great Hall Again / End of Year Again',pages:'29–30'},
    {act:'Act I',year:'Summer 1993',name:'Letters',pages:'30–32'},
    {act:'Act I',year:'Year Three',name:'Year Three',pages:'32–33'},
    {act:'Act I',year:'Year Three',name:'Electives',pages:'33–35'},
    {act:'Act I',year:'Year Three',name:'A Great Hall Slumber Party',pages:'35–39'},
    {act:'Act I',year:'Year Three',name:'FIELD TRIP!',pages:'39–40'},
    {act:'Act I',year:'Summer 1994',name:'Letters, Again',pages:'40–41'},
    {act:'Act I',year:'Year Four',name:'Goblets. Fires.',pages:'41–43'},
    {act:'Act I',year:'Year Four',name:'Not Forgivable Curses',pages:'44'},
    {act:'Act I',year:'Year Four',name:'Days Before the First Task',pages:'44–47'},
    {act:'Act I',year:'Year Four',name:'The First Task',pages:'47–50'},
    {act:'Act I',year:'Year Four',name:'Dates for the Ball',pages:'50–54'},
    {act:'Act I',year:'Year Four',name:'A Bathroom',pages:'54–56'},
    {act:'Act I',year:'Year Four',name:'The Yule-Tide Ball',pages:'56'},
    {act:'Act I',year:'Year Four',name:'The Second Task & the Subtleties of Lake Watching',pages:'57–58'},
    {act:'Act I',year:'Year Four',name:'Wayne & Cedric',pages:'59–60'},
    {act:'Act I',year:'Year Four',name:'The Third Task',pages:'60–61'},
    {act:'Act II',year:'Year Four',name:'Act II Opening',pages:'62–63'},
    {act:'Act II',year:'Summer 1995',name:'Letters Again',pages:'63'},
    {act:'Act II',year:'Year Five',name:'Welcome Back',pages:'63–64'},
    {act:'Act II',year:'Year Five',name:'Hopkins, Potter, & Emotions',pages:'64–65'},
    {act:'Act II',year:'Year Five',name:'The Rest of Year Five',pages:'65–71'},
    {act:'Act II',year:'Year Six',name:'The Dark Lord',pages:'69–71'},
    {act:'Act II',year:'Year Six',name:'Snogging 101',pages:'71–74'},
    {act:'Act II',year:'Year Six',name:'Later, in the Hallway',pages:'74'},
    {act:'Act II',year:'Year Six',name:'Perks of Love',pages:'74–76'},
    {act:'Act II',year:'Year Six',name:'Mummy',pages:'76–82'},
    {act:'Act II',year:'Year Six',name:'End of Year Six Where Nothing Major Happens',pages:'82–83'},
    {act:'Act II',year:'Summer 1997',name:'A Funeral & Instant Messaging',pages:'82–83'},
    {act:'Act II',year:'Year Seven',name:'The End Begins',pages:'83–85'},
    {act:'Act II',year:'Year Seven',name:'A Great Hall Again',pages:'85–90'},
    {act:'Act II',year:'Year Seven',name:'The Battle',pages:'90–97'},
    {act:'Act II',year:'',name:'A Very White Room',pages:'97–99'},
    {act:'Act II',year:'Nineteen Years Later',name:'Nineteen Years Blah, Blah. An Epilogue.',pages:'99–101'}
  ],
  costumes: [
    {group:'Student Base Looks',items:[
      {character:'Puff students',item:'Shared student clothing vocabulary for Years One–Four',page:'5–61',status:'Director/design decision: yellow plaid, button-up shirts, ties, and short capes; each student remains distinct.'},
      {character:'Puff students',item:'Cloaks / capes removed when regular clothes are allowed',page:'64',status:'Script required change; exact cape use by year is a director/design decision.'},
      {character:'Puff students',item:'Regular clothes for Years Five–Seven',page:'64–97',status:'Script required. Preserve each character’s established personality and aging.'},
      {character:'Student company',item:'Visible aging from eleven to eighteen',page:'1–97',status:'Director/design decision: plan small, readable changes rather than seven complete wardrobes.'},
      {character:'Puffs',item:'Yellow tournament supporter clothing',page:'48, 60',status:'Script explicitly says the Puffs are decked out in yellow.'},
      {character:'Puffs / students',item:'Halloween costumes',page:'13',status:'Script required; individual choices remain open.'},
      {character:'Puffs / dance couples',item:'Yule-Tide Ball clothing',page:'56–57',status:'Script required event; designs remain open.'},
      {character:'Company',item:'Death Buddy black hoods and masks',page:'69–70, 89–97',status:'Script required. Must support very fast changes from named roles.'}
    ]},
    {group:'Principal Characters',items:[
      {character:'Wayne Hopkins',item:'Year One student base',page:'2–22',status:'Script: eleven-year-old American boy. Director/design decision within the student vocabulary.'},
      {character:'Wayne Hopkins',item:'Cedric supporter / tournament yellow',page:'42–61',status:'Script required badge/yellow support pieces.'},
      {character:'Wayne Hopkins',item:'Disheveled Year Five look',page:'64–69',status:'Script explicitly calls him disheveled, butterbuzzed, and angsty.'},
      {character:'Wayne Hopkins',item:'Battle look',page:'89–97',status:'Director/design decision: track progressive dirt or damage only if practical.'},
      {character:'Oliver Rivers',item:'Student base with an American point of view',page:'5–61',status:'Director/design decision. Clothing should support his precise, academic personality.'},
      {character:'Oliver Rivers',item:'Year Six regular clothes',page:'71–82',status:'Script required period; relationship and growing confidence may inform the design.'},
      {character:'Oliver Rivers',item:'Tattered, dirty, and bloodied battle entrance',page:'90–91',status:'Script explicitly required.'},
      {character:'Megan Jones',item:'Darker / goth student base',page:'6–61',status:'Script explicitly says she is dressed darker and somewhat goth.'},
      {character:'Megan Jones',item:'Glasses added in Year Two',page:'25',status:'Script explicitly required.'},
      {character:'Megan Jones',item:'Yule-Tide Ball look',page:'56',status:'Script says she actually tried; exact design remains open.'},
      {character:'Megan Jones',item:'Purple or red hair accents',page:'Throughout',status:'Director/design decision: purple is the first choice.'},
      {character:'Megan Jones',item:'Battle look',page:'89–97',status:'Director/design decision: maintain the character while allowing movement and staged combat.'},
      {character:'Narrator',item:'Scholarly storyteller base',page:'1–99',status:'Script describes a scholarly type who is, at their core, a Puff.'},
      {character:'Narrator / Wayne Rivers-Jones',item:'Standard wizard robes for final sorting',page:'101',status:'Script explicitly required; this costume completes the Narrator’s identity change.'}
    ]},
    {group:'Cedric / Mr. Voldy Track',items:[
      {character:'Cedric',item:'Cool older Puff student look',page:'7–62',status:'Script establishes an immediate rock-star entrance; clothing should remain recognizably Puff.'},
      {character:'Cedric',item:'Scorched First Task version',page:'49',status:'Script explicitly says Cedric enters scorched.'},
      {character:'Cedric',item:'Towel with shorts or equivalent underneath',page:'54–55',status:'Script explicitly required for the bathroom scene.'},
      {character:'Mr. Voldy',item:'Full dark-villain look',page:'69–99',status:'Script required character; bad guys may use full robes per director direction.'},
      {character:'Mr. Voldy',item:'Weird fingers / hand silhouette',page:'69',status:'Script explicitly calls attention to his weird fingers.'},
      {character:'Mr. Voldy',item:'1981 sunglasses',page:'77–78',status:'Script explicitly required for the Blood Boogie flashback.'},
      {character:'Mr. Voldy',item:'Bare feet or visible lack of shoes',page:'86',status:'One optional monologue refers to being barefoot; only needed if that option is selected.'}
    ]},
    {group:'Ernie Mac Track',items:[
      {character:'Ernie Mac',item:'Distinct Puff student base',page:'5–97',status:'Director/design decision: proud, loud, and readable beside the other students.'},
      {character:'A Very Tall Man',item:'Large beard and goggles',page:'1',status:'Script explicitly required.'},
      {character:'A Certain Potions Teacher',item:'Greasy-haired teacher transformation',page:'10–13, 23–30, 75',status:'Script explicitly identifies greasy hair; fast-change pieces required.'},
      {character:'Professor Turban',item:'Turban with back-facing red-eye effect',page:'11–14',status:'Script explicitly required.'},
      {character:'Ghost History Teach / Mr. Nick',item:'Two clearly different ghost looks',page:'24, 27',status:'Script required roles; exact visual language remains open.'},
      {character:'Professor Locky',item:'Charming teacher look',page:'25',status:'Script describes a nice smile; design remains open.'},
      {character:'Sal',item:'Founder puppet / costume solution',page:'36–37, 78–80',status:'Script requires Sal as a puppet in the founder story.'},
      {character:'Second Headmaster',item:'Headmaster look that becomes grizzlier by Year Four',page:'35–43, 64–65, 97–98',status:'Script explicitly notes the Year Four change and later white-room return.'},
      {character:'Real Mr. Moody',item:'Large eye piece',page:'44, 53',status:'Script explicitly says the eye is the defining feature.'}
    ]},
    {group:'Hannah Track',items:[
      {character:'Hannah',item:'Quiet, specific Puff student base',page:'5–97',status:'Director/design decision; avoid making her visual identity only a joke.'},
      {character:'First Headmaster',item:'Old, kind, gentle headmaster look',page:'1, 22–30',status:'Script explicitly describes the character.'},
      {character:'Professor McG',item:'Teacher look',page:'3–12, 23–25, 47, 101',status:'Script required role; must quick-change cleanly from Hannah.'},
      {character:'Professor Sproutty',item:'Herbology teacher look',page:'12–18',status:'Script required role; greenery or plant detail is a director/design decision.'},
      {character:'Xavia Jones',item:'Menacing black witch look',page:'16, 69–80, 91–93',status:'Script explicitly introduces her clad in black.'},
      {character:'Xavia Jones',item:'Death Buddy hood reveal',page:'69–70',status:'Script requires Xavia to reveal herself from under the hood.'},
      {character:'Professor Lanny / Runes Teach / Ms. Babble',item:'Three rapid elective-teacher transformations',page:'33–35',status:'Script required roles; use minimal, unmistakable quick-change pieces.'}
    ]},
    {group:'J. Finch Fletchley Track',items:[
      {character:'J. Finch Fletchley',item:'Boyish Puff student base',page:'5–97',status:'Director/design decision; must permit highly physical comedy and battle movement.'},
      {character:'Uncle Dave',item:'New Mexico adult look',page:'1–2, 30',status:'Script required role; beer is tracked with props.'},
      {character:'Goyle',item:'Snake student identifier',page:'3–4',status:'Script required role; exact piece remains open.'},
      {character:'A Fat Friar',item:'Ghost / friar look',page:'15–18',status:'Script required role.'},
      {character:'Clumsy Longbottom',item:'Brave student look',page:'32, 50',status:'Script required role; must distinguish immediately from J. Finch.'},
      {character:'Hermeoone #3',item:'Hermeoone wig / identifier',page:'34–35',status:'Script required simultaneous third version.'},
      {character:'Viktor',item:'Intimidating Drago-Strang look',page:'41, 49, 58',status:'Script explicitly describes him as intimidating.'},
      {character:'Viktor',item:'Shark head',page:'58',status:'Script explicitly required after the Second Task.'},
      {character:'Mr. Bagman',item:'Tournament announcer look',page:'47–49',status:'Script required; quick change into Viktor may require recorded voice-over.'},
      {character:'Zach Smith',item:'Wizard-bro sports look',page:'72–73, 90',status:'Script required role; should transform instantly from J. Finch.'},
      {character:'80s Zach Smith',item:'1981 dance-club version',page:'77–78',status:'Script explicitly identifies the time-traveling 1980s version.'}
    ]},
    {group:'Sally Perks Track',items:[
      {character:'Sally Perks',item:'Ordinary Puff student base with glasses',page:'5–33',status:'Script required glasses and comparatively ordinary character presentation.'},
      {character:'Sally Perks',item:'Glasses-off version',page:'33–93',status:'Script removes her glasses in Year Three; they return during the battle.'},
      {character:'Hermeoone',item:'Hermeoone wig / identifier',page:'19, 33–35, 99',status:'Script uses a wig as the character solution.'},
      {character:'Blondo Malfoy',item:'Blonde Snake-student look',page:'12–13, 25, 99',status:'Script required role; strong silhouette and cape-twirl capability.'},
      {character:'Rowena',item:'Founder puppet / costume solution with glasses',page:'36–37, 78–80',status:'Script explicitly presents Rowena as a puppet wearing glasses.'},
      {character:'Rita Scooter',item:'Reporter transformation',page:'44–45',status:'Script required role; quick-change identifier remains open.'},
      {character:'Bippy',item:'Intentionally theatrical elf-helper look',page:'83–84, 95–96',status:'Script required; wig and prosthetic choices remain open.'}
    ]},
    {group:'Susie Bones Track',items:[
      {character:'Susie Bones',item:'Gloomy Puff student base',page:'5–97',status:'Director/design decision: visually distinct without reducing her to black clothing.'},
      {character:'Harry',item:'Recognizable hero-student look',page:'3–99',status:'Script required recurring transformation; must be extremely fast and readable.'},
      {character:'Colin',item:'Student look with camera',page:'24',status:'Script required role; camera is tracked with props.'},
      {character:'Hermeoone #2',item:'Hermeoone wig / identifier',page:'34–35',status:'Script required simultaneous second version.'},
      {character:'Ric Gryff',item:'Founder puppet / costume solution',page:'36–37, 78–80',status:'Script explicitly presents Ric as a puppet.'},
      {character:'Myrtle',item:'Young ghost-girl look',page:'54–55',status:'Script required; must quick-change around Harry/Susie demands.'}
    ]},
    {group:'Leanne Track',items:[
      {character:'Leanne',item:'Distinct Puff student base',page:'5–97',status:'Director/design decision: playful and unexpected, with full battle mobility.'},
      {character:'Ginny',item:'Student look',page:'28, 50',status:'Script required role; immediate distinction from Leanne.'},
      {character:'Helga',item:'Warm founder look',page:'36–37, 78–80',status:'Script required; may coordinate with the founder puppet vocabulary.'},
      {character:'Frenchy',item:'French wizard-school look',page:'41, 49, 58',status:'Script explicitly marks her as French; avoid relying only on stereotype.'}
    ]},
    {group:'Specialty and Ensemble',items:[
      {character:'Soul Sucking Security Guards',item:'Threatening guard / creature look',page:'31',status:'Script required sequence; scale and performer assignment remain open.'},
      {character:'Dragon',item:'Deliberately theatrical dragon look',page:'48–50',status:'Script required; performer, puppet, or hybrid solution remains open.'},
      {character:'Giant snake',item:'Snake performer / puppet treatment',page:'23, 25–29',status:'Script required; coordinate with scenic and props.'},
      {character:'Founder story company',item:'Children’s puppet-show visual language',page:'35–39, 78–80',status:'Script explicitly calls for something akin to a children’s puppet show.'},
      {character:'Doubled adult characters',item:'Hilarious, visibly artificial wigs and facial hair',page:'Throughout',status:'Director/design decision, especially for the tall man and headmasters.'},
      {character:'Student wigs',item:'Use only when they support the individual character',page:'Throughout',status:'Director/design decision; they should not distract unless personality calls for it.'}
    ]}
  ],
  props: [
    {group:'Recurring',items:[
      {item:'Wands',usedBy:'Full company',page:'Throughout'},
      {item:'Numbered year books',usedBy:'Narrator',page:'5, 23, 32, 41, 63, 71, 83'},
      {item:'The Tragic Yet Rewarding History of the Puffs',usedBy:'Cedric, Wayne, Narrator',page:'35–39, 59–62, 78–81'},
      {item:'Letters, parchment, and quills',usedBy:'Wayne, Oliver, Megan, teachers',page:'2–3, 30–32, 40–41, 63'},
      {item:'Puff, Brave, Smart, and Snake sorting items',usedBy:'Professor McG and students',page:'3–5'},
      {item:'Sorting stool and talking hat',usedBy:'Professor McG, Wayne Rivers-Jones',page:'3–5, 101'}
    ]},
    {group:'Prologue and Year One',items:[
      {item:'Light-control device',usedBy:'Narrator',page:'1'},
      {item:'Special baby',usedBy:'A Very Tall Man, First Headmaster',page:'1'},
      {item:'Wayne baby',usedBy:'Unnamed carrier, Uncle Dave',page:'1–2'},
      {item:'Beer',usedBy:'Uncle Dave',page:'1'},
      {item:'Game Boy and cartridge',usedBy:'Wayne',page:'2'},
      {item:'Owl and acceptance letter',usedBy:'Wayne',page:'2'},
      {item:'Train-platform 9 and 10 signs',usedBy:'Wayne / ensemble',page:'2–3'},
      {item:'Long curse-list parchment',usedBy:'Cedric',page:'7'},
      {item:'Training wand',usedBy:'Oliver, Professor McG',page:'11'},
      {item:'Feather',usedBy:'J. Finch, Sally',page:'11'},
      {item:'Spitball',usedBy:'Megan',page:'11'},
      {item:'Broomsticks and ball sphere',usedBy:'Harry, Blondo',page:'12–13'},
      {item:'Slug-vomit effect',usedBy:'Wayne, Oliver',page:'13'},
      {item:'Slug cleanup bag',usedBy:'Narrator',page:'13'},
      {item:'Dead owl effect',usedBy:'Oliver / ensemble',page:'13–14'},
      {item:'Ron Mop with bright red hair',usedBy:'Harry',page:'14, 29, 43, 55, 99'},
      {item:'Lantern',usedBy:'Megan',page:'15'},
      {item:'Weird mirror',usedBy:'Megan, Wayne, Oliver',page:'15–19, 80–81'},
      {item:'Prison-number sign',usedBy:'Xavia',page:'16'},
      {item:'Wiz Checkers',usedBy:'A Fat Friar, Megan',page:'16'},
      {item:'Glowing red stone',usedBy:'Megan, Narrator',page:'19'},
      {item:'Hermeoone wig',usedBy:'Harry / ensemble',page:'19, 99'},
      {item:'Hero medal',usedBy:'Wayne’s reflection',page:'19'},
      {item:'MATH certificate',usedBy:'Oliver’s reflection',page:'19'},
      {item:'Green lightsaber',usedBy:'Wayne’s reflection',page:'19, 81'}
    ]},
    {group:'Years Two and Three',items:[
      {item:'Giant snake',usedBy:'Ensemble / Harry / J. Finch',page:'23, 25–29'},
      {item:'Camera',usedBy:'Colin',page:'24'},
      {item:'Stack of books and glasses',usedBy:'Megan',page:'25'},
      {item:'Ginny’s diary',usedBy:'Ginny, Wayne',page:'28'},
      {item:'Slumber-party invitations',usedBy:'Leanne, Sally',page:'32–33'},
      {item:'Sally’s glasses',usedBy:'Sally',page:'33, 93'},
      {item:'Tea leaves',usedBy:'Professor Lanny',page:'33–34'},
      {item:'Ancient runes / rocks',usedBy:'Runes Teach, Megan',page:'34'},
      {item:'Picture of a toaster',usedBy:'Ms. Babble',page:'34'},
      {item:'Founder puppets: Rowena, Ric Gryff, and Sal',usedBy:'Company',page:'36–37, 78–80'},
      {item:'Helga’s cup',usedBy:'Helga',page:'36–37, 80'},
      {item:'Adult Butter Beverage bottles',usedBy:'Narrator and Puffs',page:'39–40'},
      {item:'Chocolate treat',usedBy:'Narrator / audience member',page:'31'}
    ]},
    {group:'Year Four and Tournament',items:[
      {item:'Cup of Fire, paper names, and fire effect',usedBy:'Second Headmaster, Narrator',page:'41–43'},
      {item:'Pro-Cedric badges',usedBy:'Puffs',page:'43–44'},
      {item:'Large eye piece',usedBy:'Real Mr. Moody',page:'44'},
      {item:'Spiders',usedBy:'Real Mr. Moody',page:'44'},
      {item:'Teddy bear',usedBy:'Cedric, Leanne',page:'44, 95'},
      {item:'Erectio gag object',usedBy:'Cedric, J. Finch',page:'45'},
      {item:'Pair of glasses',usedBy:'Cedric, Hannah',page:'45'},
      {item:'Creature-research notebook with illustrated pages',usedBy:'Wayne, Cedric',page:'45–47'},
      {item:'Bird effects for Aviafors',usedBy:'Cedric, Wayne, Professor McG',page:'46–47'},
      {item:'Audience flags',usedBy:'Puffs / audience',page:'48'},
      {item:'Microphone',usedBy:'Mr. Bagman',page:'48'},
      {item:'Dragon',usedBy:'Tournament company',page:'48–50'},
      {item:'Golden egg',usedBy:'Cedric, Wayne',page:'49, 53–55'},
      {item:'Rock-to-dog effect and dead-dog result',usedBy:'Cedric, Narrator, Dragon',page:'48–49'},
      {item:'Towel and shorts',usedBy:'Cedric',page:'54'},
      {item:'Bathroom / bathtub pieces',usedBy:'Company, Cedric, Myrtle',page:'54–55'},
      {item:'Personalized sweater',usedBy:'Ron Mop',page:'55'},
      {item:'Shark head',usedBy:'Viktor',page:'58'},
      {item:'Summoning-practice book',usedBy:'Narrator, Wayne, Cedric',page:'59–60'}
    ]},
    {group:'Years Five and Six',items:[
      {item:'Official Puffs Brand Souvenir Tissues',usedBy:'Narrator / audience member',page:'62'},
      {item:'No Being Too Sad banner',usedBy:'Hannah, Ernie',page:'63, 67'},
      {item:'Adult Butter Beverage',usedBy:'Wayne',page:'64'},
      {item:'Flavored beans',usedBy:'J. Finch',page:'66'},
      {item:'Report cards',usedBy:'Wayne, Oliver, Megan',page:'71'},
      {item:'Sports brooms, balls, and tryout equipment',usedBy:'Zach Smith and students',page:'72–73'},
      {item:'Note directing Megan to the hallway',usedBy:'Megan / Xavia',page:'74'},
      {item:'Magic donut',usedBy:'A Certain Potions Teacher',page:'75'},
      {item:'Magical bindings / ropes',usedBy:'Wayne, Oliver, Megan, Xavia',page:'76–78'},
      {item:'Captured extra wands',usedBy:'Xavia, Wayne, Oliver, Megan',page:'76–80'},
      {item:'1981 sunglasses and dance-club pieces',usedBy:'Mister Voldy and Death Buddies',page:'77–78'},
      {item:'Free-tattoo effect',usedBy:'Mister Voldy, Xavia',page:'78'},
      {item:'Glasses for Repairio',usedBy:'Oliver and the trio',page:'82'}
    ]},
    {group:'Year Seven, Battle, and Epilogue',items:[
      {item:'Computer keyboards',usedBy:'Wayne, Oliver, Megan',page:'82–83'},
      {item:'Megaphone',usedBy:'Mister Voldy',page:'85–87'},
      {item:'Board games or snacks, if used',usedBy:'Mister Voldy / Death Buddies',page:'85'},
      {item:'Tiara',usedBy:'Harry',page:'90'},
      {item:'Death Buddy masks, hoods, and wands',usedBy:'Company',page:'69–70, 89–97'},
      {item:'J. Finch’s dropped wand',usedBy:'J. Finch, Leanne',page:'94–95'},
      {item:'Expectation-animal whale, if used',usedBy:'Wayne / company',page:'93'},
      {item:'Lit memorial wands',usedBy:'Puffs',page:'82'},
      {item:'Train-platform pieces',usedBy:'Megan, Oliver, Wayne Rivers-Jones',page:'99–101'}
    ]}
  ],
  lighting: [
    {act:'Act I',cues:[
      {cue:'House lights switch off one at a time',page:'1',look:'The Narrator points the handheld device around the theatre until blackout.',status:'Script explicit'},
      {cue:'Narrator story light',page:'1',look:'Lights rise on the Narrator after the opening blackout.',status:'Script explicit'},
      {cue:'Prologue reveal areas',page:'1–3',look:'Reveal the Tall Man, First Headmaster, babies, Uncle Dave, Wayne, owl, and train-platform sequence as the story moves.',status:'Transition support'},
      {cue:'Sorting / Great Hall state',page:'3–5',look:'Open, readable school gathering for the sorting sequence.',status:'Transition support'},
      {cue:'Puff basement / common room',page:'5–10',look:'Warm basement environment with the full student company visible.',status:'Transition support'},
      {cue:'Cedric entrance',page:'7',look:'Rock-concert lighting arrives with the guitars and drums.',status:'Script explicit'},
      {cue:'Studies classroom shifts',page:'10–13',look:'Fast, clear changes between Potions, Transfiguration, Defense, Herbology, and flying.',status:'Transition support'},
      {cue:'Red eyes on the back of Professor Turban',page:'11',look:'Red glowing eyes appear when Turban turns away.',status:'Script explicit'},
      {cue:'Halloween feast',page:'13–14',look:'Festive Halloween state that can stop immediately for the troll announcement.',status:'Transition support'},
      {cue:'Common-room danger',page:'15',look:'Shift from feast energy into the basement fear huddle while footsteps sound overhead.',status:'Transition support'},
      {cue:'Forbidden classroom and weird mirror',page:'15–19',look:'Darker, ominous room with a distinct mirror area for Megan and the trio.',status:'Script explicit atmosphere'},
      {cue:'Xavia prison portrait',page:'16',look:'Isolate Xavia for the prophetic-newspaper / mug-shot introduction.',status:'Transition support'},
      {cue:'Mirror visions',page:'19',look:'Separate reflection area for Wayne’s hero vision, Oliver’s math vision, and Megan with Xavia.',status:'Script explicit staging'},
      {cue:'Year One Sports',page:'22',look:'Brief, high-energy sports event that ends quickly.',status:'Transition support'},
      {cue:'House Cup celebration and reversal',page:'22–23',look:'Celebration state for third place, then a visual shift when the decoration changes.',status:'Transition support'},
      {cue:'Year Two snake / school danger',page:'23–29',look:'Keep quick classrooms and hallways readable while allowing the snake appearances to register.',status:'Transition support'},
      {cue:'Letters isolation',page:'30–32',look:'Three separate writing areas for Wayne, Oliver, and Megan.',status:'Script explicit staging'},
      {cue:'Soul Sucking Security Guards',page:'31',look:'Chilling atmosphere, darkness, guard reveals around the theatre, giant hands, then a flash of white light.',status:'Script explicit'},
      {cue:'Year Three / electives',page:'32–35',look:'Fast classroom isolation for Divination, Runes, and Mug Studies.',status:'Transition support'},
      {cue:'Divination death shift',page:'33–34',look:'The room becomes much more ominous for the death prediction, then snaps back to normal.',status:'Script explicit'},
      {cue:'Great Hall slumber party',page:'35–39',look:'Nighttime Great Hall state that supports the Puffs sleeping across the floor.',status:'Transition support'},
      {cue:'Founder puppet story',page:'36–37',look:'Magical transition into a children’s puppet-show world, then return to the Great Hall.',status:'Script explicit'},
      {cue:'Field Trip blackout montage',page:'39–40',look:'Repeated blackouts and returns for the escalating butterbuzzed snapshots.',status:'Script explicit'},
      {cue:'Cup of Fire',page:'41–43',look:'Fire source reads clearly for champion selections; support each paper-name reveal.',status:'Script explicit effect'},
      {cue:'Cedric tournament selection',page:'42',look:'Rock-concert identity returns when Cedric is selected.',status:'Script explicit music/entrance support'},
      {cue:'Green Light Curse',page:'44',look:'Bright green light fills or strikes the stage on Avada Kedabra.',status:'Script explicit'},
      {cue:'First Task arena',page:'47–50',look:'Large tournament event with crowd visibility, champion entrances, dragon action, fire/scorch moment, and egg win.',status:'Transition and effect support'},
      {cue:'Dates for the Ball',page:'50–54',look:'Return to school hallway / neutral storytelling state.',status:'Transition support'},
      {cue:'Bathroom assembly',page:'54',look:'Support the company’s ballet-like creation of the bathroom and Cedric’s entrance.',status:'Script explicit staging'},
      {cue:'Underwater bathroom',page:'55',look:'The stage is illuminated in blue when Cedric goes underwater; return when he resurfaces.',status:'Script explicit'},
      {cue:'British Christmas transition',page:'55–56',look:'Warm seasonal shift into the Yule-Tide Ball.',status:'Transition support'},
      {cue:'Yule-Tide Ball',page:'56–57',look:'Warm dance state with enough facial visibility for Oliver and Megan’s scene.',status:'Transition support'},
      {cue:'Second Task lake watching',page:'57–58',look:'Outdoor tournament state that holds through the deliberately long lake watch.',status:'Transition support'},
      {cue:'Wayne and Cedric study area',page:'59–60',look:'Focused, quiet space for the final Wayne/Cedric scene.',status:'Transition support'},
      {cue:'Third Task crowd / maze finish',page:'60–61',look:'Warm June-evening arena; action lights and sound build when the portal opens.',status:'Script explicit atmosphere'},
      {cue:'Third Task triumph in slow motion',page:'61',look:'Hold the Puffs’ celebration in an extended, suspended image before blackout and intermission.',status:'Script explicit'}
    ]},
    {act:'Act II',cues:[
      {cue:'Act II opening green flash',page:'62',look:'Begin in darkness, then blind the audience with a flash of green before returning to the Task.',status:'Script explicit'},
      {cue:'Cedric death reveal',page:'62',look:'Shift the apparent victory into a clear, still image of Cedric’s death.',status:'Script explicit staging'},
      {cue:'Letters isolation',page:'63',look:'Separate Oliver and Megan; Wayne’s writing area remains visibly empty.',status:'Script explicit staging'},
      {cue:'Year Five common room',page:'63–64',look:'Readable return to the basement, allowing Wayne’s changed condition to register.',status:'Transition support'},
      {cue:'Wayne / Harry hallway',page:'64–65',look:'Two-door hallway state for parallel angst entrances.',status:'Transition support'},
      {cue:'A.A. meetings and Year Five montage',page:'65–69',look:'Flexible rehearsal-room state for group spells, character updates, and the Wayne/Megan/Oliver reconciliation.',status:'Transition support'},
      {cue:'Dark Lord return',page:'69–70',look:'Darker, sinister shift as cloaked Death Buddies enter; dramatic Mister Voldy reveal and lightning.',status:'Script explicit'},
      {cue:'Year Six report cards',page:'71',look:'Neutral school state for the trio before the snogging montage.',status:'Transition support'},
      {cue:'Snogging 101',page:'72',look:'Playful shift for students dancing around Wayne; keep the joke theatrical rather than overly saturated.',status:'Script explicit sequence'},
      {cue:'Sports tryouts',page:'72–73',look:'Quick open playing space for brooms, balls, and Zach Smith.',status:'Transition support'},
      {cue:'Later in the Hallway',page:'74',look:'Isolate Megan and the note; reveal Xavia cleanly.',status:'Transition support'},
      {cue:'Perks of Love',page:'74–76',look:'Private hallway / upstairs transition with clear comedy visibility.',status:'Transition support'},
      {cue:'Mummy dark room',page:'76–77',look:'Dark room with ominous tone beneath; the bound trio and Xavia remain visible.',status:'Script explicit atmosphere'},
      {cue:'1981 Blood Boogie flashback',page:'77–78',look:'Flash into an unmistakable 1980s dance-club world, then return to the dark room.',status:'Script explicit'},
      {cue:'Founder story return',page:'78–80',look:'Re-establish the children’s puppet-show vocabulary for Helga and the founders.',status:'Script explicit staging'},
      {cue:'Mirror return',page:'80–81',look:'Reveal the same weird mirror and reflection area, now showing the trio together.',status:'Script explicit'},
      {cue:'Headmaster fall',page:'82',look:'Support the skull-in-the-sky discovery, falling build, and large splat without obscuring the trio’s reaction.',status:'Script explicit staging'},
      {cue:'Funeral wand memorial',page:'82',look:'Puffs assemble as lit wands rise one by one in solidarity.',status:'Script explicit'},
      {cue:'Instant messaging',page:'82–83',look:'Three isolated keyboard positions, paralleling the earlier letter scenes.',status:'Script explicit staging'},
      {cue:'Year Seven common room / Bippy',page:'83–84',look:'Basement state with a distinct surprise entrance area for Bippy.',status:'Transition support'},
      {cue:'Great Hall ultimatum',page:'85–90',look:'Full gathering state with a separate location for amplified Mister Voldy.',status:'Transition support'},
      {cue:'Megaphone feedback reaction',page:'85',look:'Lighting may punctuate Mister Voldy’s sudden appearance without competing with the sound gag.',status:'Optional support'},
      {cue:'Battle begins',page:'89–90',look:'Immediate shift into a large, mobile war state with multiple entrances and playable areas.',status:'Script explicit sequence'},
      {cue:'Battle location tracking',page:'90–97',look:'Fast focus changes keep each Puff vignette readable while preserving the sense of one continuous battle.',status:'Transition support'},
      {cue:'Harry tiara gag',page:'90',look:'Briefly catch Harry’s tiara dance inside the chase.',status:'Script explicit staging'},
      {cue:'Oliver hero entrance',page:'90–91',look:'Dramatic, heroic reveal for Oliver’s tattered return and math sequence.',status:'Script explicit music/staging support'},
      {cue:'Xavia showdown',page:'91–93',look:'Shift music and light to signal the expected epic duel.',status:'Script explicit'},
      {cue:'Green death flashes',page:'92–96',look:'Green light punctuates the Death Buddy, Sally, J. Finch, Leanne, and Wayne death spells as called for.',status:'Script explicit'},
      {cue:'Puffs defeat the giant creature',page:'93',look:'Slow-motion company image; optional whale reveal; celebration cut off by the castle quake.',status:'Script explicit'},
      {cue:'Castle quake',page:'93',look:'Abrupt destabilizing change that breaks the unified victory image.',status:'Script explicit action'},
      {cue:'Leanne surrounded',page:'94–95',look:'Build the encirclement, isolate her two-wand fight, and land the one-legged victory image.',status:'Script explicit staging'},
      {cue:'Bippy sacrifice',page:'95–96',look:'Catch Bippy stopping the Death Buddy and hold the deliberately extended death.',status:'Script explicit staging'},
      {cue:'Wayne death / blackout',page:'96',look:'Everything goes green; Wayne falls; blackout.',status:'Script explicit'},
      {cue:'Very White Room',page:'97–98',look:'Bright white room with the Second Headmaster already waiting.',status:'Script explicit'},
      {cue:'Harry and Mister Voldy ending',page:'99',look:'Brief storybook reveal for the final vanquishing.',status:'Transition support'},
      {cue:'Epilogue train platform',page:'99–101',look:'Open platform state for Megan, Oliver, Blondo, Scorpy, and Wayne Rivers-Jones.',status:'Transition support'},
      {cue:'Final sorting',page:'101',look:'Return to magic school; isolate the elderly Professor McG, stool, hat, and Narrator before final blackout.',status:'Script explicit'}
    ]}
  ],
  sound: [
    {act:'Act I',cues:[
      {cue:'Opening light piano theme',page:'1'},
      {cue:'Owl screech / flight',page:'2'},
      {cue:'Pre-recorded Sorter Hat voice',page:'3–5'},
      {cue:'Cedric rock-concert entrance: guitars, drums, and concert energy',page:'7'},
      {cue:'Class bells for Studies and classroom transitions',page:'10–12, 23–25, 33–35'},
      {cue:'Mister Voldy whisper from Professor Turban’s turban',page:'11'},
      {cue:'House-point loss and gain stings',page:'9, 13–18'},
      {cue:'Monster Bash-style Halloween party track',page:'13'},
      {cue:'Owl plummet and impact',page:'13–14'},
      {cue:'Music screech-stop for the troll announcement',page:'14'},
      {cue:'Heavy troll footsteps above the Puff basement',page:'15'},
      {cue:'Sports commentary voice-over',page:'22'},
      {cue:'Third-place victory song',page:'22'},
      {cue:'Phoenix cry',page:'29–30'},
      {cue:'Soul Sucking Security Guards: wind, accelerating heartbeat, screams, shrieks, and release',page:'31'},
      {cue:'Second Headmaster school announcement voice-over',page:'35, 37–38'},
      {cue:'Field Trip 1990s party track and blackout-montage returns',page:'39–40'},
      {cue:'Cup of Fire / champion-selection punctuation',page:'41–43'},
      {cue:'Cedric entrance music after tournament selection',page:'42'},
      {cue:'Green Light Curse punctuation coordinated with lighting',page:'44'},
      {cue:'First Task crowd bed and champion entrance music',page:'47–48'},
      {cue:'Dragon entrance music, wrestling bell, roar, and task action',page:'48–50'},
      {cue:'Thunder and lightning before the ball-date scene',page:'50'},
      {cue:'Golden egg scream',page:'53–54'},
      {cue:'Underwater shift and Bathroom mermaid song',page:'55'},
      {cue:'Sleigh bells / British Christmas transition',page:'55'},
      {cue:'Yule-Tide Ball slow dance',page:'56'},
      {cue:'Very Short Slow Dance Song',page:'56'},
      {cue:'Upbeat Puff Rollcall dance track',page:'57'},
      {cue:'Second Task airhorn, Bagman voice-over, and splash',page:'57'},
      {cue:'Third Task action build and portal boom',page:'60–61'}
    ]},
    {act:'Act II',cues:[
      {cue:'Muffled Puff cheers under the opening darkness',page:'62'},
      {cue:'Portal boom and green-light hit',page:'62'},
      {cue:'Kiss From a Rose-style romantic sting',page:'68'},
      {cue:'Impact when Book Five hits the stage crew member',page:'69'},
      {cue:'Dark transition and lightning for Mister Voldy',page:'69–70'},
      {cue:'Sexy music for Snogging 101',page:'72'},
      {cue:'Sports tryout airhorn',page:'72'},
      {cue:'Snogging music for Wayne and Sally',page:'75'},
      {cue:'Ominous underscoring beneath Mummy',page:'76'},
      {cue:'Approaching distant scream',page:'76'},
      {cue:'1981 Blood Boogie dance track and DJ voice-over',page:'77–78'},
      {cue:'Flashback exit / return punctuation',page:'78'},
      {cue:'Falling build and large splat for the Headmaster',page:'82'},
      {cue:'Phoenix cry at the funeral',page:'82'},
      {cue:'Instant-messenger door-open sound',page:'82–83'},
      {cue:'Bippy song support, if not performed unaccompanied',page:'83–84'},
      {cue:'Megaphone feedback or siren',page:'85'},
      {cue:'Mister Voldy amplified voice, echoes, and megaphone button comedy',page:'85–87'},
      {cue:'Battle track alternating epic war score and 1990s hits',page:'90–97'},
      {cue:'Spell hits and green-light death punctuation throughout the battle',page:'90–97'},
      {cue:'Scooby-Doo-style chase music or rhythmic chase support',page:'90'},
      {cue:'Heroic math music for Oliver',page:'91'},
      {cue:'Distant slug-vomiting sound',page:'91'},
      {cue:'Xavia entrance shift',page:'91–92'},
      {cue:'Castle quake and collapse',page:'93'},
      {cue:'Large-creature attack / defeat and whale reveal, if used',page:'93'},
      {cue:'Bippy slash impact',page:'95–96'},
      {cue:'Blackout hit after Wayne is struck',page:'96'},
      {cue:'White-room transition',page:'97'},
      {cue:'Final vanquishing spell punctuation',page:'99'},
      {cue:'Epilogue / final sorting transition and blackout',page:'99–101'}
    ]}
  ]
};
