window.PUFFS_SCENE_PEOPLE = {
  'Prologue|1–5':'Narrator; Wayne; A Very Tall Man; First Headmaster; Uncle Dave; Professor McG; Seamus; Goyle; Harry; student ensemble',
  'Welcome to the Puffs|5–10':'Wayne; Oliver; Megan; Cedric; Leanne; J. Finch; Susie; Sally; Ernie; Hannah; Puffs',
  'Studies|10–12':'Wayne; Oliver; Megan; J. Finch; Sally; Leanne; Puffs; A Certain Potions Teacher; Professor McG; Professor Turban; Mister Voldy (voice); Professor Sproutty; Harry; Blondo',
  'The Feast!|13–15':'Narrator; Wayne; Oliver; Megan; J. Finch; Cedric; Puffs; Professor Turban; Harry; Ron Mop',
  'Back in the Common Room|15':'Wayne; Oliver; Cedric; J. Finch; Susie; Hannah; Sally; Puffs',
  'A Trio Is Born|15–22':'Narrator; Wayne; Oliver; Megan; A Fat Friar; Xavia; Professor Sproutty; Harry; Ron Mop; Hermeoone',
  'Wayne & Cedric|22–23':'Narrator; Wayne; Cedric; Ernie; Hannah; J. Finch; Sally; Leanne',
  'Sports!|22':'Narrator; Harry; sports players / company',
  'The End of the Year|22–23':'Narrator; First Headmaster; Cedric; Wayne; Oliver; Megan; Leanne; Puffs',
  'Year Two|23–25':'Narrator; Wayne; Oliver; Megan; A Certain Potions Teacher; Professor McG; Ghost History Teach; Colin; Professor Locky; Harry; Blondo; students',
  'Dueling Club & Harry Wants to Kill Everyone|25–26':'Narrator; Professor Locky; A Certain Potions Teacher; Harry; Blondo; J. Finch; Wayne; Puffs',
  'More Terror in the Common Room|26–27':'Wayne; Susie; J. Finch; Ernie; Sally; Puffs',
  'The Heir of Snakes|27–29':'J. Finch; Mr. Nick; giant snake; Harry; Cedric; Wayne; Oliver; Megan; Ginny',
  'A Great Hall Again / End of Year Again|29–30':'First Headmaster; A Certain Potions Teacher; Cedric; J. Finch; Megan; Harry; Ron Mop; Narrator; students / Puffs',
  'Letters|30–32':'Narrator; Wayne; Oliver; Megan; Uncle Dave',
  'Year Three|32–33':'Narrator; Wayne; Oliver; Megan; Clumsy Longbottom; Leanne; Sally',
  'Electives|33–35':'Narrator; Wayne; Megan; Oliver; Professor Lanny; Runes Teach; Ms. Babble; Hermeoone; Hermeoone #2; Hermeoone #3',
  'A Great Hall Slumber Party|35–39':'Narrator; Second Headmaster (voice); Cedric; Wayne; Oliver; Megan; Leanne; J. Finch; Susie; Hannah; Ernie; Sally; Helga; Rowena; Ric Gryff; Sal; Puffs',
  'FIELD TRIP!|39–40':'Narrator; Cedric; Wayne; Oliver; Megan; Leanne; J. Finch; Susie; Hannah; Ernie; Sally; Puffs',
  'Letters, Again|40–41':'Narrator; Wayne; Oliver; Megan',
  'Goblets. Fires.|41–43':'Narrator; Second Headmaster; Frenchy; Viktor; Cedric; Wayne; Megan; Harry; Ron Mop; Puffs / students',
  'Not Forgivable Curses|44':'Real Mr. Moody; Puffs',
  'Days Before the First Task|44–47':'Cedric; Leanne; Hannah; J. Finch; Rita Scooter; Wayne; Harry; Professor McG',
  'The First Task|47–50':'Narrator; Mr. Bagman; Cedric; Dragon; Wayne; Frenchy; Viktor; Harry; Puffs',
  'Dates for the Ball|50–54':'Wayne; Oliver; Megan; Ginny; Clumsy Longbottom; Leanne; J. Finch; Harry; Cedric; Real Mr. Moody',
  'A Bathroom|54–56':'Narrator; Cedric; Myrtle; bathroom company',
  'The Yule-Tide Ball|56':'Narrator; Wayne; Oliver; Megan; Leanne; Hannah; Cedric; Harry; Ron Mop; Puffs / dance couples',
  'The Second Task & the Subtleties of Lake Watching|57–58':'Mr. Bagman (voice); Wayne; Sally; Leanne; Narrator; Frenchy; Viktor; Harry; Puffs',
  'Wayne & Cedric|59–60':'Narrator; Wayne; Cedric',
  'The Third Task|60–61':'Narrator; Wayne; Megan; Leanne; J. Finch; Ernie; Sally; Cedric; Puffs',
  'Act II Opening|62–63':'Narrator; Wayne; Headmaster; Leanne; Hannah; Sally; Puffs',
  'Letters Again|63':'Narrator; Oliver; Megan',
  'Welcome Back|63–64':'Sally; Hannah; Ernie; Susie; Leanne; J. Finch; Wayne; Oliver; Megan; Puffs',
  'Hopkins, Potter, & Emotions|64–65':'Wayne; Harry; Second Headmaster',
  'The Rest of Year Five|65–71':'Narrator; J. Finch; Hannah; Ernie; Susie; Leanne; Sally; Wayne; Oliver; Megan; Puffs; Literal Stage Crew Member',
  'The Dark Lord|69–71':'Narrator; Mister Voldy; Death Buddies; Xavia',
  'Snogging 101|71–74':'Narrator; Wayne; Oliver; Megan; Susie; Zach Smith; Sally; students',
  'Later, in the Hallway|74':'Megan; Xavia',
  'Perks of Love|74–76':'Wayne; Sally; A Certain Potions Teacher; Narrator',
  'Mummy|76–82':'Wayne; Oliver; Megan; Xavia; Narrator; Mister Voldy; Death Buddies; 80s Zach Smith; Helga; Rowena; Ric Gryff; Sal',
  'End of Year Six Where Nothing Major Happens|82–83':'Narrator; Wayne; Oliver; Megan; Puffs',
  'A Funeral & Instant Messaging|82–83':'Narrator; Wayne; Oliver; Megan; Puffs',
  'The End Begins|83–85':'Narrator; Wayne; Megan; Bippy; Hannah; J. Finch; Leanne; Puffs',
  'A Great Hall Again|85–90':'Harry; Mister Voldy; Narrator; Wayne; Megan; Hannah; J. Finch; Leanne; Ernie; Sally; Susie; Puffs',
  'The Battle|90–97':'Full company: Wayne; Oliver; Megan; Hannah; J. Finch; Ernie; Sally; Susie; Leanne; Harry; Xavia; Zach Smith; Bippy; Death Buddies',
  'A Very White Room|97–99':'Wayne; Second Headmaster; Narrator; Harry; Mister Voldy',
  'Nineteen Years Blah, Blah. An Epilogue.|99–101':'Narrator / Wayne Rivers-Jones; Megan; Oliver; Blondo; Scorpy; Professor McG; Harry; Mister Voldy'
};
